#!/usr/bin/env bash

# languagemodel seems to be broken currently?
    #--languagemodel /opt/languagemodel \
java -jar /opt/textidote.jar \
    "$@"
status=$?
if [[ $status -eq 255 ]]; then
    exit $status;
else
    exit 0;
fi
